### ISSUE TITLE
Please use `install-powershell.sh` to replace `download.sh` in '.travis.yml'

### ISSUE THREAD

**Issue by daxian-dbw** [csm10495/cGitInfo#1]
I find the use of the powershell ['download.sh'](https://github.com/csm10495/cGitInfo/blob/74b24f17422c62325bf80a7d0ef39c4241e01775/.travis.yml#L20) from a search in Github.

The `download.sh` file under the `tools` folder of the [PowerShell repository](https://github.com/PowerShell/PowerShell) was deprecated and now is removed. Please use the `install-powershell.sh` file from the same folder to install powershell on Linux.

**Comment by csm10495** [comment]
Merged update in  dc69da9. All done here. Thanks!
